[package]
name = "nekobar"
version = "0.1.0"
edition = "2021"

[dependencies]
clashctl-core = "0.4.2"
clap = { version = "4.5.4", features = ["derive"] }
bytesize = "1.3.0"
serde_json = "1.0.117"
dirs = "5.0.1"
